FROM golang:alpine AS builder

# Stage 1 : dependencies download
WORKDIR /app
COPY src/go.mod src/go.sum ./
RUN go mod download
COPY src/ .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server

FROM alpine:latest
# Stage 2 : Simply deploy the built bin
WORKDIR /app

COPY --from=builder /server .
EXPOSE 3000

CMD ["/app/server"]