FROM golang:alpine AS builder

# Stage 1 : dependencies download
WORKDIR /app
COPY src/go.mod src/go.sum ./
RUN go mod download
COPY src/ .

RUN CGO_ENABLED=0 GOOS=linux go build -o /client

FROM alpine:latest
# Stage 2 : Simply deploy the built bin
WORKDIR /app
COPY src/assets /app/assets
COPY src/html /app/html
COPY --from=builder /client .
EXPOSE 8080

CMD ["/app/client"]