FROM golang:alpine AS builder

# Stage 1 : dependencies download
WORKDIR /app
COPY client/go.mod client/go.sum ./
RUN go mod download
COPY client/ .

RUN CGO_ENABLED=0 GOOS=linux go build -o /client

FROM alpine:latest
# Stage 2 : Simply deploy the built bin
WORKDIR /app
COPY client/assets /app/assets
COPY client/templates /app/templates
COPY --from=builder /client .
EXPOSE 80

CMD ["/app/client"]